### ISSUE TITLE
no such table: <appname_productname>.categoryproduct_ptr_id

### ISSUE THREAD

**Issue by sailorsamoor** [fivethreeo/django-shop-categories#2]
Hello, after `./manage.py syncdb` I got this messages:
Request Method:     GET
Request URL:    http://127.0.0.1:8000/admin/dalnee/article/
Django Version:     1.4.2
Exception Type:     DatabaseError
Exception Value:    

no such column: dalnee_article.categoryproduct_ptr_id

Exception Location:     /usr/home/jeltoesolnce/.virtualenvs/dalnee/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 344
Python Executable:  /usr/home/jeltoesolnce/.virtualenvs/dalnee/bin/python

My env are this: http://pastebin.com/d4s1ZuPs

That I see on dbshell:
sqlite> .schema dalnee_article
CREATE TABLE "dalnee_article" ("product_ptr_id" integer NOT NULL PRIMARY KEY, "article_note" text NOT NULL, "cover_picture" varchar(100) NOT NULL);
sqlite> 

Should I run dbshell and create the table by yourself?

**Comment by sailorsamoor** [comment]
Im sorry, not that table (above) - this: dalnee_article.categoryproduct_ptr_id, sorry agayn, I'll edit.

**Comment by fivethreeo** [comment]
This is just the db out of sync I think, drop the models or db and rerun syncdb.
