### ISSUE TITLE
related_name needed for m2m field additional_categories

### ISSUE THREAD

**Issue by michel-iamit** [fivethreeo/django-shop-categories#4]
Implementing the django-shop-categories, I get this error on syncing the db (dbsync):

Error: One or more models did not validate:
shop_categories.categoryproduct: Accessor for m2m field 'additional_categories' clashes with related m2m field 'Category.extra_product_categories'. Add a related_name argument to the definition for 'additional_categories'.
shop_categories.categoryproduct: Reverse query name for m2m field 'additional_categories' clashes with related m2m field 'Category.extra_product_categories'. Add a related_name argument to the definition for 'additional_categories'.

**Comment by fivethreeo** [comment]
Can you show your settings.py?

**Comment by michel-iamit** [comment]
the main difference with your description is i used the class in a models.py in stead of a file categories.py in folder models.
Django version 1.4.5
these are my relevant settings:

```
# django-shop config
SHOP_SHIPPING_BACKENDS = (
    'shop.shipping.backends.flat_rate.FlatRateShipping',
)

SHOP_PAYMENT_BACKENDS = (
    'shop.payment.backends.pay_on_delivery.PayOnDeliveryBackend',
    'my_shop_app_shop.payment.ExamplePayment',
)

SHOP_SHIPPING_FLAT_RATE = "10.00"

SHOP_CART_MODIFIERS = [
        'shop.cart.modifiers.tax_modifiers.TenPercentGlobalTaxModifier',
        'shop.cart.modifiers.rebate_modifiers.BulkRebateModifier',
        ]
# django-shop-categories config
SHOP_PRODUCT_MODEL = 'shop_categories.models.defaults.product.default.CategoryProduct'

SHOP_CATEGORIES_CATEGORY_MODEL = 'my_shop_app.models.Category'

INSTALLED_APPS = (
    .... my site and apps ...
    'polymorphic', # We need polymorphic installed for the shop
    'shop', # The django SHOP application
    'shop.addressmodel',
    'shop_categories',
    'shop_simplevariations',
)
```

**Comment by fivethreeo** [comment]
Ah I see now SHOP_CATEGORIES_CATEGORY_MODEL must NOT be a "real" model module. So, my_shop_app.category_models.Category, my_shop_app/category_models.py

**Comment by fivethreeo** [comment]
Fixed by changing the README

**Comment by glibersat** [comment]
Hi,
I've followed the tutorial and read 10 times the README, but I still have this issue. Is it really fixed or is there a way to fix this by a trick? Thanks!

**Comment by fivethreeo** [comment]
Hi, where did you put your extended model?

**Comment by fivethreeo** [comment]
Just make sure:

Note: Do not import the model from category.py in **init**.py, the model should NOT be in a "real" models module as this will cause the overridden Category model to be defined twice.

**Comment by fivethreeo** [comment]
Um, same for product model.

**Comment by glibersat** [comment]
Well, if I do the same for the product model, then it's not created in the database and django complains about a missing table.

**Comment by fivethreeo** [comment]
And the app with the models app_label is in installed apps?
