### ISSUE TITLE
3 level deep categories

### ISSUE THREAD

**Issue by michel-iamit** [fivethreeo/django-shop-categories#6]
See my fixture in django-shop-example pull request

All the lowest level categories are filtered out correctly.
But the firstlevel and the second level does not filter out the third level correctly.

I Am lookin into how to create a test for this... quite new with your structure of tests and virtual test environment...

**Comment by fivethreeo** [comment]
Try a Category.objects.rebuild_tree() and see if it fixes the problem.

On 19 August 2013 22:16, Michel van Leeuwen notifications@github.comwrote:

> See my fixture in django-shop-example pull request
> 
> All the lowest level categories are filtered out correctly.
> But the firstlevel and the second level does not filter out the third
> level correctly.
> 
> I Am lookin into how to create a test for this... quite new with your
> structure of tests and virtual test environment...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fivethreeo/django-shop-categories/issues/6
> .

## 

Øyvind Saltvik

**Comment by fivethreeo** [comment]
Oh, seems I forgot to take tree_id into account when filtering.

**Comment by fivethreeo** [comment]
So the test would need another top category with some subcategories, and a extra filter arg in urls.py, maybe move those views to a views.py?

**Comment by fivethreeo** [comment]
Fixed and released 1.0 to pypi
